NDefines.NGame.START_DATE = "1910.1.1.1"
NDefines.NGame.END_DATE = "1964.1.1.1"

NDefines.NCountry.EVENT_PROCESS_OFFSET = 1
NDefines.NCountry.BASE_STABILITY_WAR_FACTOR = -0.2
NDefines.NCountry.WAR_SUPPORT_DEFENSIVE_WAR = 0.2
NDefines.NCountry.BASE_MOBILIZATION_SPEED = 0.02
NDefines.NCountry.BOMBING_WAR_SUPPORT_PENALTY_SCALE = -0.00010
NDefines.NCountry.MAX_BOMBING_WEEKLY_WAR_SUPPORT_PENALTY = -0.01
NDefines.NCountry.MAX_BOMBING_WAR_SUPPORT_IMPACT = -0.2
NDefines.NCountry.HEROES_BEING_KILLED_WAR_SUPPORT_PENALTY_SCALE = -0.03
NDefines.NCountry.MAX_HEROES_BEING_KILLED_WEEKLY_WAR_SUPPORT_PENALTY = -0.03
NDefines.NCountry.MAX_HEROES_BEING_KILLED_WAR_SUPPORT_IMPACT = -0.2
NDefines.NCountry.STARTING_COMMAND_POWER = 100.0
NDefines.NCountry.BASE_MAX_COMMAND_POWER = 200.0
NDefines.NCountry.BASE_COMMAND_POWER_GAIN = 0.012
NDefines.NCountry.GIE_DIVISION_ATTACK_BONUS_AGAINST_OCCUPIER = 0.05
NDefines.NCountry.GIE_DIVISION_DEFENSE_BONUS_AGAINST_OCCUPIER = 0.05
NDefines.NCountry.GIE_DIVISION_ATTACK_BONUS_ON_CORE = 0.05
NDefines.NCountry.GIE_DIVISION_DEFENSE_BONUS_ON_CORE = 0.05
NDefines.NCountry.GIE_ESCAPING_DIVISIONS_EQUIPMENT_RATIO = 0.1
NDefines.NCountry.MIN_POSSIBLE_TRAINING_MANPOWER = 300000

NDefines.NTechnology.BASE_RESEARCH_POINTS_SAVED = 60.0
NDefines.NTechnology.BASE_TECH_COST = 90
NDefines.NTechnology.DEFAULT_XP_RESEARCH_COST = 200

NDefines.NPolitics.DEFAULT_OCCUPATION_POLICY = 3

NDefines.NBuildings.ANTI_AIR_SUPERIORITY_MULT = 7.5
NDefines.NBuildings.MAX_BUILDING_LEVELS = 25

NDefines.NDeployment.BASE_DEPLOYMENT_TRAINING = 1.5

NDefines.NMilitary.DIVISION_SIZE_FOR_XP = 1
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 90

NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 4
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 1
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 5
NDefines.NMilitary.COMBAT_MINIMUM_TIME = 2
NDefines.NMilitary.BASE_LEADER_TRAIT_GAIN_XP = 0.75
NDefines.NMilitary.TRAINING_ATTRITION = 0.03
NDefines.NMilitary.TRAINING_MIN_STRENGTH = 0.25
NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.01
NDefines.NMilitary.PLANNING_MAX = 0.4
NDefines.NMilitary.PLAN_EXECUTE_CAREFUL_MAX_FORT = 7
NDefines.NMilitary.FRONT_MIN_PATH_TO_REDEPLOY = 6
NDefines.NMilitary.UNIT_LEADER_ASSIGN_TRAIT_COST = 10.0
NDefines.NMilitary.XP_GAIN_PER_OVERRUN_UNIT = 10.0
NDefines.NMilitary.XP_GAIN_FOR_SHATTERING = 10.0
NDefines.NMilitary.AIR_WING_MAX_SIZE = 2000

NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_LOW = 0.65
NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_MED = 0.55
NDefines.NAI.ORG_UNIT_STRONG = 0.6
NDefines.NAI.STR_UNIT_STRONG = 0.70
NDefines.NAI.STR_UNIT_WEAK = 0.3
NDefines.NAI.LAND_COMBAT_CAS_PER_COMBAT = 200

NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 20
